name: Metrics
on:
  # Schedule updates (each day at 6 AM UTC - better for global visibility)
  schedule: [{cron: "0 6 * * *"}]
  # Manual trigger and on pushes to main
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic config
          user: shaheem-pp
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Toronto
          
          # Core plugins for product engineers
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          
          # Coding habits and patterns
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 21
          plugin_habits_facts: yes
          plugin_habits_from: 365
          
          # Recent activity (last 2 weeks)
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_limit: 4
          plugin_activity_visibility: all
          
          # Achievement highlights
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact
          plugin_achievements_limit: 4
          
          # Lines of code (productivity metric)
          plugin_lines: yes
          plugin_lines_sections: base
          
          # Notable work (for product impact)
          plugin_notable: yes
          plugin_notable_types: commit, pull_request
          
          # Traffic insights (if available)
          plugin_traffic: yes
